// <auto-generated by scripts/generate_section4_matrix_tests.py>
using BeDemo.Api.Models;
using BeDemo.Api.Models.DTOs;
using BeDemo.Api.Models.Requests.Albums;
using BeDemo.Api.Models.Requests.Auth;
using BeDemo.Api.Models.Requests.Blogs;
using BeDemo.Api.Models.Requests.Common;
using BeDemo.Api.Models.Requests.Faces;
using BeDemo.Api.Models.Requests.Moderation;
using BeDemo.Api.Models.Requests.OAuth;
using BeDemo.Api.Models.Requests.Pages;
using BeDemo.Api.Models.Requests.Profile;
using BeDemo.Api.Models.Requests.Reels;
using BeDemo.Api.Models.Requests.Social;
using BeDemo.Api.Models.Requests.Stats;
using BeDemo.Api.Models.Requests.Stories;
using BeDemo.Api.Models.Requests.Users;
using BeDemo.Api.Validation.Albums;
using BeDemo.Api.Validation.Auth;
using BeDemo.Api.Validation.Blogs;
using BeDemo.Api.Validation.Common;
using BeDemo.Api.Validation.Faces;
using BeDemo.Api.Validation.Files;
using BeDemo.Api.Validation.Filters;
using BeDemo.Api.Validation.Moderation;
using BeDemo.Api.Validation.OAuth;
using BeDemo.Api.Validation.Pages;
using BeDemo.Api.Validation.Profile;
using BeDemo.Api.Validation.Reels;
using BeDemo.Api.Validation.Rules;
using BeDemo.Api.Validation.Social;
using BeDemo.Api.Validation.Stats;
using BeDemo.Api.Validation.Stories;
using BeDemo.Api.Validation.Users;
using FluentAssertions;
using FluentValidation;
using Microsoft.AspNetCore.Http;
using Xunit;

namespace BeDemo.Api.Tests.Validation;

public sealed class ValidatorSection4MatrixTests
{
    private static FormFile CreateImageFormFile()
    {
        var bytes = new byte[] { 0x89, 0x50, 0x4E, 0x47 };
        return new FormFile(new MemoryStream(bytes), 0, bytes.Length, "a", "a.png")
        {
            Headers = new HeaderDictionary(),
            ContentType = "image/png",
        };
    }

    [Fact] public void T1_AlbumByUserQueryValidator_invalid_fails() =>
        new AlbumByUserQueryValidator().Validate(new AlbumByUserQuery { FaceId = -1 }).IsValid.Should().BeFalse();

    [Fact] public void T11_AlbumByUserQueryValidator_valid_minimal_passes() =>
        new AlbumByUserQueryValidator().Validate(new AlbumByUserQuery { FaceId = 1 }).IsValid.Should().BeTrue();

    [Fact] public void T1_AlbumListQueryValidator_invalid_fails() =>
        new AlbumListQueryValidator().Validate(new AlbumListQuery { FaceId = -1 }).IsValid.Should().BeFalse();

    [Fact] public void T11_AlbumListQueryValidator_valid_minimal_passes() =>
        new AlbumListQueryValidator().Validate(new AlbumListQuery { FaceId = 1 }).IsValid.Should().BeTrue();

    [Fact] public void T1_CreateAlbumCommentRequestValidator_invalid_fails() =>
        new CreateAlbumCommentRequestValidator().Validate(new CreateAlbumCommentDto { Content = "" }).IsValid.Should().BeFalse();

    [Fact] public void T11_CreateAlbumCommentRequestValidator_valid_minimal_passes() =>
        new CreateAlbumCommentRequestValidator().Validate(new CreateAlbumCommentDto { Content = "x" }).IsValid.Should().BeTrue();

    [Fact] public void T1_CreateAlbumRequestValidator_invalid_fails() =>
        new CreateAlbumRequestValidator().Validate(new CreateAlbumDto()).IsValid.Should().BeFalse();

    [Fact] public void T11_CreateAlbumRequestValidator_valid_minimal_passes() =>
        new CreateAlbumRequestValidator().Validate(new CreateAlbumDto { Title = "T" }).IsValid.Should().BeTrue();

    [Fact] public void T1_UpdateAlbumCommentRequestValidator_invalid_fails() =>
        new UpdateAlbumCommentRequestValidator().Validate(new UpdateAlbumCommentDto { Content = "" }).IsValid.Should().BeFalse();

    [Fact] public void T11_UpdateAlbumCommentRequestValidator_valid_minimal_passes() =>
        new UpdateAlbumCommentRequestValidator().Validate(new UpdateAlbumCommentDto { Content = "x" }).IsValid.Should().BeTrue();

    [Fact] public void T1_UpdateAlbumRequestValidator_invalid_fails() =>
        new UpdateAlbumRequestValidator().Validate(new UpdateAlbumDto { Title = new string('x', 500) }).IsValid.Should().BeFalse();

    [Fact] public void T11_UpdateAlbumRequestValidator_valid_minimal_passes() =>
        new UpdateAlbumRequestValidator().Validate(new UpdateAlbumDto { Title = "T" }).IsValid.Should().BeTrue();

    [Fact] public void T1_LoginRequestValidator_invalid_fails() =>
        new LoginRequestValidator().Validate(new LoginModel()).IsValid.Should().BeFalse();

    [Fact] public void T11_LoginRequestValidator_valid_minimal_passes() =>
        new LoginRequestValidator().Validate(new LoginModel { Email = "a@b.com", Password = "secret" }).IsValid.Should().BeTrue();

    [Fact] public void T1_RegisterRequestValidator_invalid_fails() =>
        new RegisterRequestValidator().Validate(new RegisterModel()).IsValid.Should().BeFalse();

    [Fact] public void T11_RegisterRequestValidator_valid_minimal_passes() =>
        new RegisterRequestValidator().Validate(new RegisterModel { Email = "a@b.com", Password = "Test1234!@##" }).IsValid.Should().BeTrue();

    [Fact] public void T1_BlogListQueryValidator_invalid_fails() =>
        new BlogListQueryValidator().Validate(new BlogListQuery { FaceId = -1 }).IsValid.Should().BeFalse();

    [Fact] public void T11_BlogListQueryValidator_valid_minimal_passes() =>
        new BlogListQueryValidator().Validate(new BlogListQuery { FaceId = 1 }).IsValid.Should().BeTrue();

    [Fact] public void T1_CreateBlogCommentRequestValidator_invalid_fails() =>
        new CreateBlogCommentRequestValidator().Validate(new CreateBlogCommentDto { Content = "" }).IsValid.Should().BeFalse();

    [Fact] public void T11_CreateBlogCommentRequestValidator_valid_minimal_passes() =>
        new CreateBlogCommentRequestValidator().Validate(new CreateBlogCommentDto { Content = "x" }).IsValid.Should().BeTrue();

    [Fact] public void T1_CreateBlogRequestValidator_invalid_fails() =>
        new CreateBlogRequestValidator().Validate(new CreateBlogDto()).IsValid.Should().BeFalse();

    [Fact] public void T11_CreateBlogRequestValidator_valid_minimal_passes() =>
        new CreateBlogRequestValidator().Validate(new CreateBlogDto { Title = "T", Content = "C", FaceId = 1 }).IsValid.Should().BeTrue();

    [Fact] public void T1_UpdateBlogCommentRequestValidator_invalid_fails() =>
        new UpdateBlogCommentRequestValidator().Validate(new UpdateBlogCommentDto { Content = "" }).IsValid.Should().BeFalse();

    [Fact] public void T11_UpdateBlogCommentRequestValidator_valid_minimal_passes() =>
        new UpdateBlogCommentRequestValidator().Validate(new UpdateBlogCommentDto { Content = "x" }).IsValid.Should().BeTrue();

    [Fact] public void T1_UpdateBlogRequestValidator_invalid_fails() =>
        new UpdateBlogRequestValidator().Validate(new UpdateBlogDto { Title = new string('x', 500) }).IsValid.Should().BeFalse();

    [Fact] public void T11_UpdateBlogRequestValidator_valid_minimal_passes() =>
        new UpdateBlogRequestValidator().Validate(new UpdateBlogDto { Title = "T" }).IsValid.Should().BeTrue();

    [Fact] public void T1_ChatMessagesQueryValidator_invalid_fails() =>
        new ChatMessagesQueryValidator().Validate(new ChatMessagesQuery { PageSize = 0 }).IsValid.Should().BeFalse();

    [Fact] public void T11_ChatMessagesQueryValidator_valid_minimal_passes() =>
        new ChatMessagesQueryValidator().Validate(new ChatMessagesQuery { PageSize = 20 }).IsValid.Should().BeTrue();

    [Fact] public void T1_CreateFaceChatRoomRequestValidator_invalid_fails() =>
        new CreateFaceChatRoomRequestValidator().Validate(new CreateFaceChatRoomDto()).IsValid.Should().BeFalse();

    [Fact] public void T11_CreateFaceChatRoomRequestValidator_valid_minimal_passes() =>
        new CreateFaceChatRoomRequestValidator().Validate(new CreateFaceChatRoomDto { Title = "T" }).IsValid.Should().BeTrue();

    [Fact] public void T1_CreateFaceRequestValidator_invalid_fails() =>
        new CreateFaceRequestValidator().Validate(new CreateFaceModel()).IsValid.Should().BeFalse();

    [Fact] public void T11_CreateFaceRequestValidator_valid_minimal_passes() =>
        new CreateFaceRequestValidator().Validate(new CreateFaceModel { Index = "x", Title = "T" }).IsValid.Should().BeTrue();

    [Fact] public void T1_CreateSystemFaceChatRoomRequestValidator_invalid_fails() =>
        new CreateSystemFaceChatRoomRequestValidator().Validate(new CreateSystemFaceChatRoomDto()).IsValid.Should().BeFalse();

    [Fact] public void T11_CreateSystemFaceChatRoomRequestValidator_valid_minimal_passes() =>
        new CreateSystemFaceChatRoomRequestValidator().Validate(new CreateSystemFaceChatRoomDto { Title = "T" }).IsValid.Should().BeTrue();

    [Fact] public void T1_FaceProfileCommentRequestValidator_invalid_fails() =>
        new FaceProfileCommentRequestValidator().Validate(new FaceProfileCommentDto()).IsValid.Should().BeFalse();

    [Fact] public void T11_FaceProfileCommentRequestValidator_valid_minimal_passes() =>
        new FaceProfileCommentRequestValidator().Validate(new FaceProfileCommentDto { Body = "b" }).IsValid.Should().BeTrue();

    [Fact] public void T1_FaceProfileReviewRequestValidator_invalid_fails() =>
        new FaceProfileReviewRequestValidator().Validate(new FaceProfileReviewDto()).IsValid.Should().BeFalse();

    [Fact] public void T11_FaceProfileReviewRequestValidator_valid_minimal_passes() =>
        new FaceProfileReviewRequestValidator().Validate(new FaceProfileReviewDto { Title = "T", Text = "x", Stars = 5 }).IsValid.Should().BeTrue();

    [Fact] public void T1_SetMyFaceRoleRequestValidator_invalid_fails() =>
        new SetMyFaceRoleRequestValidator().Validate(new SetMyFaceRoleModel()).IsValid.Should().BeFalse();

    [Fact] public void T11_SetMyFaceRoleRequestValidator_valid_minimal_passes() =>
        new SetMyFaceRoleRequestValidator().Validate(new SetMyFaceRoleModel { UserRoleId = 1 }).IsValid.Should().BeTrue();

    [Fact] public void T1_UpdateFaceChatRoomRequestValidator_invalid_fails() =>
        new UpdateFaceChatRoomRequestValidator().Validate(new UpdateFaceChatRoomDto { Title = new string('x', 500) }).IsValid.Should().BeFalse();

    [Fact] public void T11_UpdateFaceChatRoomRequestValidator_valid_minimal_passes() =>
        new UpdateFaceChatRoomRequestValidator().Validate(new UpdateFaceChatRoomDto { Title = "T" }).IsValid.Should().BeTrue();

    [Fact] public void T1_UpdateFaceRequestValidator_invalid_fails() =>
        new UpdateFaceRequestValidator().Validate(new UpdateFaceModel { Title = new string('x', 500) }).IsValid.Should().BeFalse();

    [Fact] public void T11_UpdateFaceRequestValidator_valid_minimal_passes() =>
        new UpdateFaceRequestValidator().Validate(new UpdateFaceModel { Title = "T" }).IsValid.Should().BeTrue();

    [Fact] public void T1_WallTicketCommentRequestValidator_invalid_fails() =>
        new WallTicketCommentRequestValidator().Validate(new WallTicketCommentDto()).IsValid.Should().BeFalse();

    [Fact] public void T11_WallTicketCommentRequestValidator_valid_minimal_passes() =>
        new WallTicketCommentRequestValidator().Validate(new WallTicketCommentDto { Content = "c" }).IsValid.Should().BeTrue();

    [Fact] public void T1_WallTicketWriteRequestValidator_invalid_fails() =>
        new WallTicketWriteRequestValidator().Validate(new WallTicketWriteDto()).IsValid.Should().BeFalse();

    [Fact] public void T11_WallTicketWriteRequestValidator_valid_minimal_passes() =>
        new WallTicketWriteRequestValidator().Validate(new WallTicketWriteDto { Title = "T", Description = "D" }).IsValid.Should().BeTrue();

    [Fact] public void T1_BulkModerationRequestValidator_invalid_fails() =>
        new BulkModerationRequestValidator().Validate(new BulkModerationRequest(BeDemo.Api.Models.Requests.Moderation.BulkModerationAction.Approve, new List<BulkModerationItemDto>(), null, null)).IsValid.Should().BeFalse();

    [Fact] public void T11_BulkModerationRequestValidator_valid_minimal_passes() =>
        new BulkModerationRequestValidator().Validate(new BulkModerationRequest(BeDemo.Api.Models.Requests.Moderation.BulkModerationAction.Approve, new List<BulkModerationItemDto> { new(ModeratedContentType.Blog, 1) }, null, null)).IsValid.Should().BeTrue();

    [Fact] public void T1_GetModerationQueueQueryValidator_invalid_fails() =>
        new GetModerationQueueQueryValidator().Validate(new GetModerationQueueQuery { MinConfidence = 0.9, MaxConfidence = 0.1 }).IsValid.Should().BeFalse();

    [Fact] public void T11_GetModerationQueueQueryValidator_valid_minimal_passes() =>
        new GetModerationQueueQueryValidator().Validate(new GetModerationQueueQuery { FaceId = 1 }).IsValid.Should().BeTrue();

    [Fact] public void T1_AdminInviteListQueryValidator_invalid_fails() =>
        new AdminInviteListQueryValidator().Validate(new AdminInviteListQuery { Take = 0 }).IsValid.Should().BeFalse();

    [Fact] public void T11_AdminInviteListQueryValidator_valid_minimal_passes() =>
        new AdminInviteListQueryValidator().Validate(new AdminInviteListQuery { Skip = 0, Take = 10 }).IsValid.Should().BeTrue();

    [Fact] public void T1_RegisterPrefillQueryValidator_invalid_fails() =>
        new RegisterPrefillQueryValidator().Validate(new RegisterPrefillQuery()).IsValid.Should().BeFalse();

    [Fact] public void T11_RegisterPrefillQueryValidator_valid_minimal_passes() =>
        new RegisterPrefillQueryValidator().Validate(new RegisterPrefillQuery { Hash = "abc" }).IsValid.Should().BeTrue();

    [Fact] public void T1_RegisterResendDtoValidator_invalid_fails() =>
        new RegisterResendDtoValidator().Validate(new RegisterResendDto()).IsValid.Should().BeFalse();

    [Fact] public void T11_RegisterResendDtoValidator_valid_minimal_passes() =>
        new RegisterResendDtoValidator().Validate(new RegisterResendDto { Email = "a@b.com" }).IsValid.Should().BeTrue();

    [Fact] public void T1_RegisterSignupRequestValidator_invalid_fails() =>
        new RegisterSignupRequestValidator().Validate(new RegisterRequestDto()).IsValid.Should().BeFalse();

    [Fact] public void T11_RegisterSignupRequestValidator_valid_minimal_passes() =>
        new RegisterSignupRequestValidator().Validate(new RegisterRequestDto { Email = "a@b.com" }).IsValid.Should().BeTrue();

    [Fact] public void T1_CreatePageComponentRequestValidator_invalid_fails() =>
        new CreatePageComponentRequestValidator().Validate(new CreatePageComponentDto()).IsValid.Should().BeFalse();

    [Fact] public void T11_CreatePageComponentRequestValidator_valid_minimal_passes() =>
        new CreatePageComponentRequestValidator().Validate(new CreatePageComponentDto { PageId = 1, ComponentTypeId = 1, DisplayModeId = 1 }).IsValid.Should().BeTrue();

    [Fact] public void T1_CreatePageRequestValidator_invalid_fails() =>
        new CreatePageRequestValidator().Validate(new CreatePageModel()).IsValid.Should().BeFalse();

    [Fact] public void T11_CreatePageRequestValidator_valid_minimal_passes() =>
        new CreatePageRequestValidator().Validate(new CreatePageModel { FaceId = 1, PageTypeId = 1, Name = "N", Path = "/p", Index = 0 }).IsValid.Should().BeTrue();

    [Fact] public void T1_CreatePageTypeRequestValidator_invalid_fails() =>
        new CreatePageTypeRequestValidator().Validate(new CreatePageTypeModel()).IsValid.Should().BeFalse();

    [Fact] public void T11_CreatePageTypeRequestValidator_valid_minimal_passes() =>
        new CreatePageTypeRequestValidator().Validate(new CreatePageTypeModel { Index = "home" }).IsValid.Should().BeTrue();

    [Fact] public void T1_GetPagesQueryValidator_invalid_fails() =>
        new GetPagesQueryValidator().Validate(new GetPagesQuery { FaceId = -1 }).IsValid.Should().BeFalse();

    [Fact] public void T11_GetPagesQueryValidator_valid_minimal_passes() =>
        new GetPagesQueryValidator().Validate(new GetPagesQuery { FaceId = 1 }).IsValid.Should().BeTrue();

    [Fact] public void T1_UpdatePageComponentRequestValidator_invalid_fails() =>
        new UpdatePageComponentRequestValidator().Validate(new UpdatePageComponentDto { Label = new string('x', 500) }).IsValid.Should().BeFalse();

    [Fact] public void T11_UpdatePageComponentRequestValidator_valid_minimal_passes() =>
        new UpdatePageComponentRequestValidator().Validate(new UpdatePageComponentDto { Label = "L" }).IsValid.Should().BeTrue();

    [Fact] public void T1_UpdatePageRequestValidator_invalid_fails() =>
        new UpdatePageRequestValidator().Validate(new UpdatePageModel { GridSchema = new string('x', 100_001) }).IsValid.Should().BeFalse();

    [Fact] public void T11_UpdatePageRequestValidator_valid_minimal_passes() =>
        new UpdatePageRequestValidator().Validate(new UpdatePageModel { Name = "N" }).IsValid.Should().BeTrue();

    [Fact] public void T1_UpdatePageTypeRequestValidator_invalid_fails() =>
        new UpdatePageTypeRequestValidator().Validate(new UpdatePageTypeModel { Index = new string('x', 100) }).IsValid.Should().BeFalse();

    [Fact] public void T11_UpdatePageTypeRequestValidator_valid_minimal_passes() =>
        new UpdatePageTypeRequestValidator().Validate(new UpdatePageTypeModel { Index = "home" }).IsValid.Should().BeTrue();

    [Fact] public void T1_UpsertPageTranslationsRequestValidator_invalid_fails() =>
        new UpsertPageTranslationsRequestValidator().Validate(new UpsertPageTranslationsRequest()).IsValid.Should().BeFalse();

    [Fact] public void T11_UpsertPageTranslationsRequestValidator_valid_minimal_passes() =>
        new UpsertPageTranslationsRequestValidator().Validate(new UpsertPageTranslationsRequest { Translations = [new PageTranslationItem { LanguageCode = "en", TranslatedRoute = "/x" }] }).IsValid.Should().BeTrue();

    [Fact] public void T1_AvatarUploadRequestValidator_invalid_fails() =>
        new AvatarUploadRequestValidator().Validate(new AvatarUploadRequest()).IsValid.Should().BeFalse();

    [Fact] public void T11_AvatarUploadRequestValidator_valid_minimal_passes() =>
        new AvatarUploadRequestValidator().Validate(new AvatarUploadRequest { File = new FormFile(Stream.Null, 0, 1, "a", "a.png") }).IsValid.Should().BeTrue();

    [Fact] public void T1_FaceAvatarUploadRequestValidator_invalid_fails() =>
        new FaceAvatarUploadRequestValidator().Validate(new FaceAvatarUploadRequest()).IsValid.Should().BeFalse();

    [Fact] public void T11_FaceAvatarUploadRequestValidator_valid_minimal_passes() =>
        new FaceAvatarUploadRequestValidator().Validate(new FaceAvatarUploadRequest { FaceId = 1, File = CreateImageFormFile() }).IsValid.Should().BeTrue();

    [Fact] public void T1_ProfileMeQueryValidator_invalid_fails() =>
        new ProfileMeQueryValidator().Validate(new ProfileMeQuery { FaceId = -1 }).IsValid.Should().BeFalse();

    [Fact] public void T11_ProfileMeQueryValidator_valid_minimal_passes() =>
        new ProfileMeQueryValidator().Validate(new ProfileMeQuery { FaceId = 1 }).IsValid.Should().BeTrue();

    [Fact] public void T1_UpdateProfileRequestValidator_invalid_fails() =>
        new UpdateProfileRequestValidator().Validate(new UpdateProfileRequest()).IsValid.Should().BeFalse();

    [Fact] public void T11_UpdateProfileRequestValidator_valid_minimal_passes() =>
        new UpdateProfileRequestValidator().Validate(new UpdateProfileRequest { FirstName = "A" }).IsValid.Should().BeTrue();

    [Fact] public void T1_CreateReelCommentRequestValidator_invalid_fails() =>
        new CreateReelCommentRequestValidator().Validate(new CreateReelCommentDto { Content = "" }).IsValid.Should().BeFalse();

    [Fact] public void T11_CreateReelCommentRequestValidator_valid_minimal_passes() =>
        new CreateReelCommentRequestValidator().Validate(new CreateReelCommentDto { Content = "x" }).IsValid.Should().BeTrue();

    [Fact] public void T1_CreateReelRequestValidator_invalid_fails() =>
        new CreateReelRequestValidator().Validate(new CreateReelDto()).IsValid.Should().BeFalse();

    [Fact] public void T11_CreateReelRequestValidator_valid_minimal_passes() =>
        new CreateReelRequestValidator().Validate(new CreateReelDto { Title = "T", VideoUrl = "https://example.com/v.mp4" }).IsValid.Should().BeTrue();

    [Fact] public void T1_ReelByUserQueryValidator_invalid_fails() =>
        new ReelByUserQueryValidator().Validate(new ReelByUserQuery { FaceId = -1 }).IsValid.Should().BeFalse();

    [Fact] public void T11_ReelByUserQueryValidator_valid_minimal_passes() =>
        new ReelByUserQueryValidator().Validate(new ReelByUserQuery { FaceId = 1 }).IsValid.Should().BeTrue();

    [Fact] public void T1_ReelCommentCreateQueryValidator_invalid_fails() =>
        new ReelCommentCreateQueryValidator().Validate(new ReelCommentCreateQuery { FaceId = -1 }).IsValid.Should().BeFalse();

    [Fact] public void T11_ReelCommentCreateQueryValidator_valid_minimal_passes() =>
        new ReelCommentCreateQueryValidator().Validate(new ReelCommentCreateQuery { FaceId = 1 }).IsValid.Should().BeTrue();

    [Fact] public void T1_ReelDetailQueryValidator_invalid_fails() =>
        new ReelDetailQueryValidator().Validate(new ReelDetailQuery { FaceId = -1 }).IsValid.Should().BeFalse();

    [Fact] public void T11_ReelDetailQueryValidator_valid_minimal_passes() =>
        new ReelDetailQueryValidator().Validate(new ReelDetailQuery { FaceId = 1 }).IsValid.Should().BeTrue();

    [Fact] public void T1_ReelListQueryValidator_invalid_fails() =>
        new ReelListQueryValidator().Validate(new ReelListQuery { FaceId = -1 }).IsValid.Should().BeFalse();

    [Fact] public void T11_ReelListQueryValidator_valid_minimal_passes() =>
        new ReelListQueryValidator().Validate(new ReelListQuery { FaceId = 1 }).IsValid.Should().BeTrue();

    [Fact] public void T1_UpdateReelCommentRequestValidator_invalid_fails() =>
        new UpdateReelCommentRequestValidator().Validate(new UpdateReelCommentDto { Content = "" }).IsValid.Should().BeFalse();

    [Fact] public void T11_UpdateReelCommentRequestValidator_valid_minimal_passes() =>
        new UpdateReelCommentRequestValidator().Validate(new UpdateReelCommentDto { Content = "x" }).IsValid.Should().BeTrue();

    [Fact] public void T1_UpdateReelRequestValidator_invalid_fails() =>
        new UpdateReelRequestValidator().Validate(new UpdateReelDto { Title = new string('x', 500) }).IsValid.Should().BeFalse();

    [Fact] public void T11_UpdateReelRequestValidator_valid_minimal_passes() =>
        new UpdateReelRequestValidator().Validate(new UpdateReelDto { Title = "T" }).IsValid.Should().BeTrue();

    [Fact] public void T1_BlockUserRequestValidator_invalid_fails() =>
        new BlockUserRequestValidator().Validate(new BlockUserDto()).IsValid.Should().BeFalse();

    [Fact] public void T11_BlockUserRequestValidator_valid_minimal_passes() =>
        new BlockUserRequestValidator().Validate(new BlockUserDto { BlockedId = "u" }).IsValid.Should().BeTrue();

    [Fact] public void T1_FollowUserRequestValidator_invalid_fails() =>
        new FollowUserRequestValidator().Validate(new FollowUserDto()).IsValid.Should().BeFalse();

    [Fact] public void T11_FollowUserRequestValidator_valid_minimal_passes() =>
        new FollowUserRequestValidator().Validate(new FollowUserDto { FollowedId = "u" }).IsValid.Should().BeTrue();

    [Fact] public void T1_MessageHistoryQueryValidator_invalid_fails() =>
        new MessageHistoryQueryValidator().Validate(new MessageHistoryQuery { Limit = 0 }).IsValid.Should().BeFalse();

    [Fact] public void T11_MessageHistoryQueryValidator_valid_minimal_passes() =>
        new MessageHistoryQueryValidator().Validate(new MessageHistoryQuery { Limit = 50 }).IsValid.Should().BeTrue();

    [Fact] public void T1_NotificationsListQueryValidator_invalid_fails() =>
        new NotificationsListQueryValidator().Validate(new NotificationsListQuery { Limit = 0 }).IsValid.Should().BeFalse();

    [Fact] public void T11_NotificationsListQueryValidator_valid_minimal_passes() =>
        new NotificationsListQueryValidator().Validate(new NotificationsListQuery { Limit = 50 }).IsValid.Should().BeTrue();

    [Fact] public void T1_SendFriendRequestRequestValidator_invalid_fails() =>
        new SendFriendRequestRequestValidator().Validate(new SendFriendRequestDto()).IsValid.Should().BeFalse();

    [Fact] public void T11_SendFriendRequestRequestValidator_valid_minimal_passes() =>
        new SendFriendRequestRequestValidator().Validate(new SendFriendRequestDto { ReceiverId = "u" }).IsValid.Should().BeTrue();

    [Fact] public void T1_StatsTimeseriesQueryValidator_invalid_fails() =>
        new StatsTimeseriesQueryValidator().Validate(new StatsTimeseriesQuery { Metric = "", FromUtc = DateTime.UtcNow, ToUtc = DateTime.UtcNow.AddDays(-1), Bucket = "day" }).IsValid.Should().BeFalse();

    [Fact] public void T11_StatsTimeseriesQueryValidator_valid_minimal_passes() =>
        new StatsTimeseriesQueryValidator().Validate(new StatsTimeseriesQuery { Metric = "users", FromUtc = DateTime.UtcNow.AddDays(-7), ToUtc = DateTime.UtcNow, Bucket = "day" }).IsValid.Should().BeTrue();

    [Fact] public void T1_CreateStoryCommentRequestValidator_invalid_fails() =>
        new CreateStoryCommentRequestValidator().Validate(new CreateStoryCommentDto { Content = "" }).IsValid.Should().BeFalse();

    [Fact] public void T11_CreateStoryCommentRequestValidator_valid_minimal_passes() =>
        new CreateStoryCommentRequestValidator().Validate(new CreateStoryCommentDto { Content = "x" }).IsValid.Should().BeTrue();

    [Fact] public void T1_CreateStoryRequestValidator_invalid_fails() =>
        new CreateStoryRequestValidator().Validate(new CreateStoryDto()).IsValid.Should().BeFalse();

    [Fact] public void T11_CreateStoryRequestValidator_valid_minimal_passes() =>
        new CreateStoryRequestValidator().Validate(new CreateStoryDto { Title = "T" }).IsValid.Should().BeTrue();

    [Fact] public void T1_PublishStoryRequestValidator_invalid_fails() =>
        new PublishStoryRequestValidator().Validate(new PublishStoryDto { ScheduledPublishAt = DateTime.UtcNow.AddDays(-1) }).IsValid.Should().BeFalse();

    [Fact] public void T11_PublishStoryRequestValidator_valid_minimal_passes() =>
        new PublishStoryRequestValidator().Validate(new PublishStoryDto()).IsValid.Should().BeTrue();

    [Fact] public void T1_StoryDetailQueryValidator_invalid_fails() =>
        new StoryDetailQueryValidator().Validate(new StoryDetailQuery()).IsValid.Should().BeFalse();

    [Fact] public void T11_StoryDetailQueryValidator_valid_minimal_passes() =>
        new StoryDetailQueryValidator().Validate(new StoryDetailQuery { FaceId = 1 }).IsValid.Should().BeTrue();

    [Fact] public void T1_StoryImageUploadFormValidator_invalid_fails() =>
        new StoryImageUploadFormValidator().Validate(new StoryImageUploadForm()).IsValid.Should().BeFalse();

    [Fact] public void T11_StoryImageUploadFormValidator_valid_minimal_passes() =>
        new StoryImageUploadFormValidator().Validate(new StoryImageUploadForm { File = CreateImageFormFile(), SortOrder = 0 }).IsValid.Should().BeTrue();

    [Fact] public void T1_StoryListQueryValidator_invalid_fails() =>
        new StoryListQueryValidator().Validate(new StoryListQuery()).IsValid.Should().BeFalse();

    [Fact] public void T11_StoryListQueryValidator_valid_minimal_passes() =>
        new StoryListQueryValidator().Validate(new StoryListQuery { FaceId = 1 }).IsValid.Should().BeTrue();

    [Fact] public void T1_StoryMineQueryValidator_invalid_fails() =>
        new StoryMineQueryValidator().Validate(new StoryMineQuery { FaceId = -1 }).IsValid.Should().BeFalse();

    [Fact] public void T11_StoryMineQueryValidator_valid_minimal_passes() =>
        new StoryMineQueryValidator().Validate(new StoryMineQuery()).IsValid.Should().BeTrue();

    [Fact] public void T1_StoryScopedQueryValidator_invalid_fails() =>
        new StoryScopedQueryValidator().Validate(new StoryScopedQuery()).IsValid.Should().BeFalse();

    [Fact] public void T11_StoryScopedQueryValidator_valid_minimal_passes() =>
        new StoryScopedQueryValidator().Validate(new StoryScopedQuery { FaceId = 1 }).IsValid.Should().BeTrue();

    [Fact] public void T1_StoryViewQueryValidator_invalid_fails() =>
        new StoryViewQueryValidator().Validate(new StoryViewQuery()).IsValid.Should().BeFalse();

    [Fact] public void T11_StoryViewQueryValidator_valid_minimal_passes() =>
        new StoryViewQueryValidator().Validate(new StoryViewQuery { FaceId = 1 }).IsValid.Should().BeTrue();

    [Fact] public void T1_CreateUserRequestValidator_invalid_fails() =>
        new CreateUserRequestValidator().Validate(new CreateUserModel()).IsValid.Should().BeFalse();

    [Fact] public void T11_CreateUserRequestValidator_valid_minimal_passes() =>
        new CreateUserRequestValidator().Validate(new CreateUserModel { Email = "a@b.com", Password = "Test1234!@##" }).IsValid.Should().BeTrue();

    [Fact] public void T1_GetUsersQueryValidator_invalid_fails() =>
        new GetUsersQueryValidator().Validate(new GetUsersQuery { Page = 0 }).IsValid.Should().BeFalse();

    [Fact] public void T11_GetUsersQueryValidator_valid_minimal_passes() =>
        new GetUsersQueryValidator().Validate(new GetUsersQuery { Page = 1, PageSize = 10 }).IsValid.Should().BeTrue();

    [Fact] public void T1_RegisterPushTokenRequestValidator_invalid_fails() =>
        new RegisterPushTokenRequestValidator().Validate(new RegisterPushTokenRequestDto()).IsValid.Should().BeFalse();

    [Fact] public void T11_RegisterPushTokenRequestValidator_valid_minimal_passes() =>
        new RegisterPushTokenRequestValidator().Validate(new RegisterPushTokenRequestDto { RegistrationToken = "0123456789", Platform = "ios" }).IsValid.Should().BeTrue();

    [Fact] public void T1_UpdateUserRequestValidator_invalid_fails() =>
        new UpdateUserRequestValidator().Validate(new UpdateUserModel { Password = "short" }).IsValid.Should().BeFalse();

    [Fact] public void T11_UpdateUserRequestValidator_valid_minimal_passes() =>
        new UpdateUserRequestValidator().Validate(new UpdateUserModel { FirstName = "A" }).IsValid.Should().BeTrue();
    // Skipped matrix (add to SAMPLES in generator): AdminCreateRegistrationInviteDto, FaceProfileListQuery, PaginationQuery, WallTicketListQuery

}
